services:
  - type: web
    name: car-damage-backend
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: SEVERITY_MODEL_URL
        value: "https://huggingface.co/suhas-5324/car-damage-models/resolve/main/convnextb_finetuned.pth"
      - key: TYPE_MODEL_URL
        value: "https://huggingface.co/suhas-5324/car-damage-models/resolve/main/mobilenetv3_large_100_type_best.pth"
      # - key: YOLO_MODEL_URL
      #   value: "https://huggingface.co/YOUR_USERNAME/YOUR_REPO/resolve/main/best.pt"
      - key: HF_TOKEN
        sync: false  # set this manually in Render dashboard (if repo is private)
      - key: CORS_ALLOW_ORIGINS
        value: "https://your-vercel-app.vercel.app"